// ===================== MOCK DATA STORE =====================
// Centralized in-memory data for all modules
// Every entity carries company_id so multi-company tenants are isolated.

// ── helpers ──────────────────────────────────────────────────
let _seqId = 1000;
export function nextId(prefix = ''): string {
  _seqId++;
  return prefix ? `${prefix}-${_seqId}` : String(_seqId);
}

// ── Companies ────────────────────────────────────────────────
export const mockCompanies: any[] = [
  {
    id: 1,
    name: 'Empresa Demo S.A.',
    tax_id: 'J-12345678-9',
    address: 'Av. Principal #123, Caracas',
    phone: '+58 212-555-0001',
    email: 'contacto@empresademo.com',
    logo_path: null,
    is_active: true,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-06-01T08:30:00Z',
  },
  {
    id: 2,
    name: 'Distribuidora Norte C.A.',
    tax_id: 'J-98765432-1',
    address: 'Calle 10 #45, Valencia',
    phone: '+58 241-555-0002',
    email: 'info@distnorte.com',
    logo_path: null,
    is_active: true,
    created_at: '2024-02-20T14:00:00Z',
    updated_at: '2024-07-15T11:00:00Z',
  },
  {
    id: 3,
    name: 'Servicios Integrales XYZ',
    tax_id: 'J-55667788-0',
    address: 'Centro Comercial Plaza, Local 5, Maracaibo',
    phone: '+58 261-555-0003',
    email: 'admin@servxyz.com',
    logo_path: null,
    is_active: false,
    created_at: '2024-03-10T09:00:00Z',
    updated_at: '2024-05-20T16:00:00Z',
  },
];

// ── Warehouses ───────────────────────────────────────────────
export const mockWarehouses: any[] = [
  {
    id: 'wh-001',
    companyId: 1,
    name: 'Almacén Central',
    code: 'ALM-001',
    address: 'Av. Principal #123, Caracas',
    manager: null,
    phone: null,
    isActive: true,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-06-01T08:30:00Z',
  },
  {
    id: 'wh-002',
    companyId: 1,
    name: 'Almacén Secundario',
    code: 'ALM-002',
    address: 'Zona Industrial, Galpón 5',
    manager: null,
    phone: null,
    isActive: true,
    createdAt: '2024-02-01T10:00:00Z',
    updatedAt: '2024-06-01T08:30:00Z',
  },
  {
    id: 'wh-003',
    companyId: 2,
    name: 'Depósito Norte',
    code: 'DEP-001',
    address: 'Calle 10 #45, Valencia',
    manager: null,
    phone: null,
    isActive: true,
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-06-01T08:30:00Z',
  },
];

// ── Inventory (per company) ──────────────────────────────────
export const mockInventory: any[] = [
  // Company 1
  {
    productCode: 'PROD-001',
    productName: 'Laptop Dell Inspiron 15',
    productDescription: 'Laptop Dell Inspiron 15, 8GB RAM, 256GB SSD',
    productUnit: 'und',
    entries: 50,
    exits: 15,
    stock: 35,
    stockLimit: 10,
    unitPrice: 850.0,
    warehouse: 'Almacén Central',
    entity: 'Empresa Demo S.A.',
    companyId: 1,
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  {
    productCode: 'PROD-002',
    productName: 'Monitor Samsung 24"',
    productDescription: 'Monitor Samsung 24 pulgadas Full HD',
    productUnit: 'und',
    entries: 100,
    exits: 45,
    stock: 55,
    stockLimit: 20,
    unitPrice: 320.0,
    warehouse: 'Almacén Central',
    entity: 'Empresa Demo S.A.',
    companyId: 1,
    createdAt: '2024-02-15T14:00:00Z',
    updatedAt: '2024-06-05T14:00:00Z',
  },
  {
    productCode: 'PROD-003',
    productName: 'Teclado Mecánico Logitech',
    productDescription: 'Teclado mecánico RGB Logitech G Pro',
    productUnit: 'und',
    entries: 200,
    exits: 180,
    stock: 20,
    stockLimit: 30,
    unitPrice: 75.0,
    warehouse: 'Almacén Central',
    entity: 'Empresa Demo S.A.',
    companyId: 1,
    createdAt: '2024-03-01T09:00:00Z',
    updatedAt: '2024-06-10T09:00:00Z',
  },
  {
    productCode: 'PROD-004',
    productName: 'Mouse Inalámbrico',
    productDescription: 'Mouse inalámbrico ergonómico Logitech MX',
    productUnit: 'und',
    entries: 150,
    exits: 60,
    stock: 90,
    stockLimit: 25,
    unitPrice: 45.0,
    warehouse: 'Almacén Secundario',
    entity: 'Empresa Demo S.A.',
    companyId: 1,
    createdAt: '2024-03-10T11:30:00Z',
    updatedAt: '2024-06-12T08:00:00Z',
  },
  {
    productCode: 'PROD-005',
    productName: 'Cable HDMI 2m',
    productDescription: 'Cable HDMI 2.1 de alta velocidad, 2 metros',
    productUnit: 'und',
    entries: 300,
    exits: 250,
    stock: 50,
    stockLimit: 50,
    unitPrice: 12.5,
    warehouse: 'Almacén Central',
    entity: 'Empresa Demo S.A.',
    companyId: 1,
    createdAt: '2024-04-05T08:00:00Z',
    updatedAt: '2024-06-15T16:00:00Z',
  },
  {
    productCode: 'PROD-006',
    productName: 'Disco Duro Externo 1TB',
    productDescription: 'Disco duro externo Seagate 1TB USB 3.0',
    productUnit: 'und',
    entries: 80,
    exits: 30,
    stock: 50,
    stockLimit: 15,
    unitPrice: 65.0,
    warehouse: 'Almacén Central',
    entity: 'Empresa Demo S.A.',
    companyId: 1,
    createdAt: '2024-04-20T13:00:00Z',
    updatedAt: '2024-04-20T13:00:00Z',
  },
  {
    productCode: 'PROD-007',
    productName: 'Memoria USB 64GB',
    productDescription: 'Memoria USB Kingston 64GB 3.0',
    productUnit: 'und',
    entries: 500,
    exits: 350,
    stock: 150,
    stockLimit: 50,
    unitPrice: 8.5,
    warehouse: 'Almacén Central',
    entity: 'Empresa Demo S.A.',
    companyId: 1,
    createdAt: '2024-05-01T07:00:00Z',
    updatedAt: '2024-05-01T07:00:00Z',
  },
  {
    productCode: 'PROD-008',
    productName: 'Webcam HD 1080p',
    productDescription: 'Webcam Logitech C920 HD Pro',
    productUnit: 'und',
    entries: 60,
    exits: 40,
    stock: 20,
    stockLimit: 10,
    unitPrice: 95.0,
    warehouse: 'Almacén Secundario',
    entity: 'Empresa Demo S.A.',
    companyId: 1,
    createdAt: '2024-05-15T15:00:00Z',
    updatedAt: '2024-05-15T15:00:00Z',
  },
  // Company 2
  {
    productCode: 'PROD-N01',
    productName: 'Arroz Premium 1kg',
    productDescription: 'Arroz grano largo premium',
    productUnit: 'kg',
    entries: 1000,
    exits: 600,
    stock: 400,
    stockLimit: 200,
    unitPrice: 2.5,
    warehouse: 'Depósito Norte',
    entity: 'Distribuidora Norte C.A.',
    companyId: 2,
    createdAt: '2024-02-20T14:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  {
    productCode: 'PROD-N02',
    productName: 'Aceite Vegetal 1L',
    productDescription: 'Aceite de girasol refinado',
    productUnit: 'L',
    entries: 500,
    exits: 300,
    stock: 200,
    stockLimit: 100,
    unitPrice: 3.8,
    warehouse: 'Depósito Norte',
    entity: 'Distribuidora Norte C.A.',
    companyId: 2,
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
];

// ── Purchase products (line items) ──────────────────────────
export const mockPurchaseProducts: any[] = [
  {
    id: 'pp-001',
    purchaseId: 'pur-001',
    productCode: 'PROD-001',
    productName: 'Laptop Dell Inspiron 15',
    quantity: 10,
    unitPrice: 850.0,
    totalPrice: 8500.0,
    productUnit: 'und',
  },
  {
    id: 'pp-002',
    purchaseId: 'pur-001',
    productCode: 'PROD-002',
    productName: 'Monitor Samsung 24"',
    quantity: 20,
    unitPrice: 320.0,
    totalPrice: 6400.0,
    productUnit: 'und',
  },
  {
    id: 'pp-003',
    purchaseId: 'pur-002',
    productCode: 'PROD-N01',
    productName: 'Arroz Premium 1kg',
    quantity: 500,
    unitPrice: 2.5,
    totalPrice: 1250.0,
    productUnit: 'kg',
  },
  {
    id: 'pp-004',
    purchaseId: 'pur-003',
    productCode: 'PROD-004',
    productName: 'Mouse Inalámbrico',
    quantity: 25,
    unitPrice: 45.0,
    totalPrice: 1125.0,
    productUnit: 'und',
  },
];

// ── Purchases ────────────────────────────────────────────────
export const mockPurchases: any[] = [
  {
    id: 'pur-001',
    companyId: 1,
    entity: 'Empresa Demo S.A.',
    warehouse: 'Almacén Central',
    supplier: 'TechSupply Venezuela',
    document: 'FAC-2024-001',
    status: 'completed',
    created_at: '2024-06-01T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
  },
  {
    id: 'pur-002',
    companyId: 2,
    entity: 'Distribuidora Norte C.A.',
    warehouse: 'Depósito Norte',
    supplier: 'Global Electronics',
    document: 'FAC-2024-005',
    status: 'completed',
    created_at: '2024-05-20T11:00:00Z',
    updated_at: '2024-05-20T11:00:00Z',
  },
  {
    id: 'pur-003',
    companyId: 1,
    entity: 'Empresa Demo S.A.',
    warehouse: 'Almacén Secundario',
    supplier: 'Office Pro',
    document: 'FAC-2024-010',
    status: 'pending',
    created_at: '2024-06-20T09:00:00Z',
    updated_at: '2024-06-20T09:00:00Z',
  },
];

// ── Movements ────────────────────────────────────────────────
export const mockMovements: any[] = [
  {
    id: 'mov-001',
    companyId: 1,
    movementType: 'entry',
    productCode: 'PROD-001',
    quantity: 10,
    reason: 'Compra FAC-2024-001',
    label: null,
    userName: 'Admin',
    purchaseId: 'pur-001',
    createdAt: '2024-06-01T10:00:00Z',
  },
  {
    id: 'mov-002',
    companyId: 1,
    movementType: 'exit',
    productCode: 'PROD-002',
    quantity: 5,
    reason: 'Despacho a sucursal Valencia',
    label: null,
    userName: 'Admin',
    purchaseId: null,
    createdAt: '2024-06-05T14:30:00Z',
  },
  {
    id: 'mov-003',
    companyId: 2,
    movementType: 'entry',
    productCode: 'PROD-N01',
    quantity: 500,
    reason: 'Compra FAC-2024-005',
    label: null,
    userName: 'Admin',
    purchaseId: 'pur-002',
    createdAt: '2024-05-20T11:00:00Z',
  },
  {
    id: 'mov-004',
    companyId: 1,
    movementType: 'entry',
    productCode: 'PROD-004',
    quantity: 25,
    reason: 'Reposición de inventario',
    label: null,
    userName: 'Admin',
    purchaseId: null,
    createdAt: '2024-06-12T08:00:00Z',
  },
  {
    id: 'mov-005',
    companyId: 1,
    movementType: 'exit',
    productCode: 'PROD-005',
    quantity: 50,
    reason: 'Venta a cliente mayorista',
    label: null,
    userName: 'Admin',
    purchaseId: null,
    createdAt: '2024-06-15T16:00:00Z',
  },
];

// ── Reception Reports ────────────────────────────────────────
export const mockReceptionReports: any[] = [
  {
    id: 'rr-001',
    purchaseId: 'pur-001',
    companyId: 1,
    details: JSON.stringify({
      entity: 'Empresa Demo S.A.',
      warehouse: 'Almacén Central',
      supplier: 'TechSupply Venezuela',
      document: 'FAC-2024-001',
      documentType: 'Factura',
      complies: true,
      products: [
        {
          code: 'PROD-001',
          description: 'Laptop Dell Inspiron 15',
          quantity: 10,
          unitPrice: 850.0,
          unit: 'und',
          amount: 8500.0,
        },
        {
          code: 'PROD-002',
          description: 'Monitor Samsung 24"',
          quantity: 20,
          unitPrice: 320.0,
          unit: 'und',
          amount: 6400.0,
        },
      ],
    }),
    createdByName: 'Admin',
    createdAt: '2024-06-01T10:00:00Z',
  },
  {
    id: 'rr-002',
    purchaseId: 'pur-002',
    companyId: 2,
    details: JSON.stringify({
      entity: 'Distribuidora Norte C.A.',
      warehouse: 'Depósito Norte',
      supplier: 'Global Electronics',
      document: 'FAC-2024-005',
      documentType: 'Factura',
      complies: true,
      products: [
        {
          code: 'PROD-N01',
          description: 'Arroz Premium 1kg',
          quantity: 500,
          unitPrice: 2.5,
          unit: 'kg',
          amount: 1250.0,
        },
      ],
    }),
    createdByName: 'Admin',
    createdAt: '2024-05-20T11:00:00Z',
  },
];

// ── Delivery Reports (vales de entrega / devolución) ─────────
export const mockDeliveryReports: any[] = [
  {
    id: 'dr-001',
    purchaseId: null,
    companyId: 1,
    code: 'VE-PROD-002',
    entity: 'Entrega Directa',
    warehouse: 'Almacén Central',
    document: 'SALIDA-MOV002',
    products: JSON.stringify([
      {
        code: 'PROD-002',
        description: 'Monitor Samsung 24"',
        quantity: 5,
        unit: 'und',
        unitPrice: 320.0,
        amount: 1600.0,
      },
    ]),
    date: '2024-06-05T14:30:00Z',
    reportType: 'Vale de Entrega',
    reason: 'Despacho a sucursal Valencia',
    createdByName: 'Admin',
  },
];

// ── Invoices (per company) ───────────────────────────────────
export const mockInvoices: any[] = [
  {
    id: 'inv-001',
    companyId: 1,
    invoiceNumber: 'INV-2024-0001',
    customerName: 'Carlos Rodríguez',
    customerId: 'CLI-001',
    customerAddress: 'Av. Libertador #456, Caracas',
    customerPhone: '+58 212-555-1234',
    date: '2024-06-01',
    subtotal: 2550.0,
    taxRate: 16,
    taxAmount: 408.0,
    discount: 50.0,
    total: 2908.0,
    status: 'paid',
    notes: 'Pago recibido por transferencia',
    createdByName: 'Admin',
    createdAt: '2024-06-01T10:00:00Z',
    updatedAt: '2024-06-02T08:00:00Z',
  },
  {
    id: 'inv-002',
    companyId: 1,
    invoiceNumber: 'INV-2024-0002',
    customerName: 'María González',
    customerId: 'CLI-002',
    customerAddress: 'Calle 5 #78, Valencia',
    customerPhone: '+58 241-555-5678',
    date: '2024-06-05',
    subtotal: 1600.0,
    taxRate: 16,
    taxAmount: 256.0,
    discount: 0,
    total: 1856.0,
    status: 'pending',
    notes: '',
    createdByName: 'Admin',
    createdAt: '2024-06-05T14:00:00Z',
    updatedAt: '2024-06-05T14:00:00Z',
  },
  {
    id: 'inv-003',
    companyId: 1,
    invoiceNumber: 'INV-2024-0003',
    customerName: 'Pedro Martínez',
    customerId: 'CLI-003',
    customerAddress: 'Urbanización Las Palmas, Maracaibo',
    customerPhone: '+58 261-555-9012',
    date: '2024-06-10',
    subtotal: 375.0,
    taxRate: 16,
    taxAmount: 60.0,
    discount: 25.0,
    total: 410.0,
    status: 'cancelled',
    notes: 'Cancelada por solicitud del cliente',
    createdByName: 'Admin',
    createdAt: '2024-06-10T09:00:00Z',
    updatedAt: '2024-06-11T15:00:00Z',
  },
];

// ── Invoice Items ────────────────────────────────────────────
export const mockInvoiceItems: any[] = [
  {
    id: 'ii-001',
    invoiceId: 'inv-001',
    productCode: 'PROD-001',
    description: 'Laptop Dell Inspiron 15',
    quantity: 3,
    unitPrice: 850.0,
    amount: 2550.0,
  },
  {
    id: 'ii-002',
    invoiceId: 'inv-002',
    productCode: 'PROD-002',
    description: 'Monitor Samsung 24"',
    quantity: 5,
    unitPrice: 320.0,
    amount: 1600.0,
  },
  {
    id: 'ii-003',
    invoiceId: 'inv-003',
    productCode: 'PROD-003',
    description: 'Teclado Mecánico Logitech',
    quantity: 5,
    unitPrice: 75.0,
    amount: 375.0,
  },
];

// ── Fixed Assets (per company) - real depreciation catalog ───
export const mockFixedAssets: any[] = [
  {
    id: 1,
    companyId: 1,
    asset_code: 'AF-2024-001',
    name: 'Servidor Dell PowerEdge',
    description: 'Servidor Dell PowerEdge R740, 64GB RAM',
    group_number: 2,
    subgroup: 'Equipos de computación',
    subgroup_detail: 'c)',
    depreciation_rate: 25,
    acquisition_value: 12000.0,
    current_value: 9000.0,
    acquisition_date: '2024-01-15',
    location: 'Data Center Principal',
    responsible_person: 'Carlos IT',
    status: 'active',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-06-01T08:30:00Z',
  },
  {
    id: 2,
    companyId: 1,
    asset_code: 'AF-2024-002',
    name: 'Camioneta Toyota Hilux',
    description: 'Camioneta Toyota Hilux 2024 4x4',
    group_number: 3,
    subgroup: 'Otros terrestres',
    subgroup_detail: 'c) Terrestre Otros',
    depreciation_rate: 20,
    acquisition_value: 35000.0,
    current_value: 28000.0,
    acquisition_date: '2024-02-20',
    location: 'Estacionamiento Central',
    responsible_person: 'Pedro Logística',
    status: 'active',
    created_at: '2024-02-20T14:00:00Z',
    updated_at: '2024-07-01T10:00:00Z',
  },
  {
    id: 3,
    companyId: 1,
    asset_code: 'AF-2024-003',
    name: 'Mobiliario de Oficina',
    description: 'Set de escritorios y sillas ergonómicas',
    group_number: 2,
    subgroup: 'Muebles y estantes',
    subgroup_detail: 'a)',
    depreciation_rate: 10,
    acquisition_value: 5000.0,
    current_value: 4500.0,
    acquisition_date: '2024-03-10',
    location: 'Oficina 3er Piso',
    responsible_person: 'María Admin',
    status: 'active',
    created_at: '2024-03-10T09:00:00Z',
    updated_at: '2024-06-15T11:00:00Z',
  },
  {
    id: 4,
    companyId: 1,
    asset_code: 'AF-2023-010',
    name: 'Impresora Industrial',
    description: 'Impresora multifuncional HP LaserJet Pro',
    group_number: 2,
    subgroup: 'Enseres y equipos de oficina',
    subgroup_detail: 'b)',
    depreciation_rate: 15,
    acquisition_value: 3500.0,
    current_value: 1750.0,
    acquisition_date: '2023-06-01',
    location: 'Área de Impresión',
    responsible_person: 'Ana Soporte',
    status: 'disposed',
    created_at: '2023-06-01T08:00:00Z',
    updated_at: '2024-06-01T12:00:00Z',
  },
];

// ── Depreciation Catalog (Cuban regulations) ─────────────────
export const mockDepreciationCatalog = [
  {
    group_number: 1,
    group_name: 'Edificaciones y otras construcciones',
    subgroups: [
      {
        name: 'Edificaciones de madera o plástico',
        detail: 'a) Edificaciones',
        rate: 6.0,
      },
      {
        name: 'Edificaciones de panelería',
        detail: 'a) Edificaciones',
        rate: 5.0,
      },
      {
        name: 'Edificaciones de mampostería y otros materiales',
        detail: 'a) Edificaciones',
        rate: 3.0,
      },
      {
        name: 'Puentes de acero, hierro u hormigón',
        detail: 'b) Otras construcciones',
        rate: 3.0,
      },
      {
        name: 'Puentes de madera',
        detail: 'b) Otras construcciones',
        rate: 6.0,
      },
      {
        name: 'Muelles, espigones o embarcaderos de madera',
        detail: 'b) Otras construcciones',
        rate: 6.0,
      },
      {
        name: 'Muelles, espigones o embarcaderos de hormigón reforzado',
        detail: 'b) Otras construcciones',
        rate: 3.0,
      },
      {
        name: 'Diques secos y flotantes, varaderos',
        detail: 'b) Otras construcciones',
        rate: 6.0,
      },
      { name: 'Silos y tanques', detail: 'b) Otras construcciones', rate: 6.0 },
      { name: 'Otras no clasificadas', detail: 'c) Otras', rate: 3.0 },
    ],
  },
  {
    group_number: 2,
    group_name: 'Muebles, enseres y equipos de oficina',
    subgroups: [
      { name: 'Muebles y estantes', detail: 'a)', rate: 10.0 },
      { name: 'Enseres y equipos de oficina', detail: 'b)', rate: 15.0 },
      { name: 'Equipos de computación', detail: 'c)', rate: 25.0 },
    ],
  },
  {
    group_number: 3,
    group_name: 'Equipos no tecnológicos',
    subgroups: [
      { name: 'Aéreo', detail: 'a)', rate: 20.0 },
      { name: 'Marítimo', detail: 'b)', rate: 6.0 },
      {
        name: 'Equipos de transporte ferroviario',
        detail: 'c) Terrestre I',
        rate: 6.0,
      },
      { name: 'Otros terrestres', detail: 'c) Terrestre Otros', rate: 20.0 },
    ],
  },
  {
    group_number: 4,
    group_name: 'Maquinaria en general',
    subgroups: [{ name: 'Maquinaria en general', detail: '', rate: 6.0 }],
  },
  {
    group_number: 5,
    group_name: 'Animales',
    subgroups: [
      { name: 'Animales de trabajo', detail: 'a)', rate: 10.0 },
      {
        name: 'Ganado mayor (recría, leche o carne)',
        detail: 'b)',
        rate: 100.0,
      },
    ],
  },
  {
    group_number: 6,
    group_name: 'Plantaciones agrícolas permanentes',
    subgroups: [
      {
        name: 'Plantaciones agrícolas permanentes',
        detail: 'General',
        rate: 15.0,
      },
      { name: 'Plantaciones de Piña', detail: 'a) Piña', rate: 50.0 },
    ],
  },
  {
    group_number: 7,
    group_name: 'Otros activos',
    subgroups: [{ name: 'Otros activos', detail: '', rate: 15.0 }],
  },
];

// ── Stock Limits ─────────────────────────────────────────────
export const mockStockLimits: any[] = [
  {
    id: 'sl-001',
    companyId: 1,
    productCode: 'PROD-001',
    productName: 'Laptop Dell Inspiron 15',
    warehouseId: 'wh-001',
    warehouseName: 'Almacén Central',
    minStock: 10,
    maxStock: 100,
    currentStock: 35,
    reorderPoint: 15,
    isActive: true,
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-06-01T08:30:00Z',
  },
  {
    id: 'sl-002',
    companyId: 1,
    productCode: 'PROD-003',
    productName: 'Teclado Mecánico Logitech',
    warehouseId: 'wh-001',
    warehouseName: 'Almacén Central',
    minStock: 30,
    maxStock: 200,
    currentStock: 20,
    reorderPoint: 40,
    isActive: true,
    createdAt: '2024-03-01T09:00:00Z',
    updatedAt: '2024-06-01T08:30:00Z',
  },
  {
    id: 'sl-003',
    companyId: 1,
    productCode: 'PROD-005',
    productName: 'Cable HDMI 2m',
    warehouseId: 'wh-002',
    warehouseName: 'Almacén Secundario',
    minStock: 50,
    maxStock: 500,
    currentStock: 50,
    reorderPoint: 80,
    isActive: true,
    createdAt: '2024-04-05T08:00:00Z',
    updatedAt: '2024-06-01T08:30:00Z',
  },
];

// ── Users ────────────────────────────────────────────────────
export const mockUsers: any[] = [
  {
    id: 'user-001',
    email: 'admin@nexum.com',
    password: 'admin123',
    firstName: 'Admin',
    lastName: 'NEXUM',
    role: 'admin',
    tenantId: 'tenant-multi-1',
    tenantName: 'Grupo Empresarial Demo',
    tenantType: 'MULTI_COMPANY',
  },
  {
    id: 'user-002',
    email: 'usuario@nexum.com',
    password: 'user123',
    firstName: 'Usuario',
    lastName: 'Demo',
    role: 'user',
    tenantId: 'tenant-single-1',
    tenantName: 'Empresa Demo S.A.',
    tenantType: 'SINGLE_COMPANY',
  },
  {
    id: 'user-003',
    email: 'dev@nexum.com',
    password: 'dev123',
    firstName: 'Developer',
    lastName: 'Mode',
    role: 'superadmin',
    tenantId: 'tenant-dev',
    tenantName: 'Tenant Desarrollo',
    tenantType: 'MULTI_COMPANY',
  },
];

// ── Helper: get depreciation rate from catalog ───────────────
export function getDepreciationRate(
  groupNumber: number,
  subgroupName: string,
): number | null {
  const group = mockDepreciationCatalog.find(
    (g) => g.group_number === groupNumber,
  );
  if (!group) return null;
  const sub = group.subgroups.find((s) => s.name === subgroupName);
  return sub ? sub.rate : null;
}
